<?php

/**
 * @file
 * Set Poster/Thumbnail for Mediaelement Module.
 * Assuming the following fields on node:
 *  field_iaeavideo_url (type=link)   (display format: MediaElement Video)
 *  field_iaeavideo_poster (type=file) (display format: hidden) *OR* field_poster_url (type=link) (display format: hidden)
 *
 * Create an image style called 'video_poster' which can be used to scale the image if necessary if using a file,
 * otherwise if using a link, the poster image will be scaled to fit based on width and height of the video.
 */

/*
 * implements hook_preprocess_HOOK()
 */
function mediaelement_poster_preprocess_field(&$variables, $hook) {

  if ($variables['element']['#field_name'] == 'field_iaeavideo_url') {
    if (!empty($variables['element']['#object']->field_iaeavideo_poster[$variables['element']['#language']])) {
      $file_uri = $variables['element']['#object']->field_iaeavideo_poster[$variables['element']['#language']][0]['uri'];
      $image_url = image_style_url('iaea_video_poster', $file_uri);
      $variables['items'][0]['#attributes']['poster'] = $image_url;
    } 
    elseif (!empty($variables['element']['#object']->field_poster_url[$variables['element']['#language']])) {
      $file_url = $variables['element']['#object']->field_poster_url[$variables['element']['#language']][0]['url'];
      $variables['items'][0]['#attributes']['poster'] = $file_url;
    }
  }
}

