<?php
/**
 * @file
 * iaea_apachesolr_configuration.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function iaea_apachesolr_configuration_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'GiIy4zr9Gu0ZSa0bumw1Y9qIIpIDf1wu',
    'disabled' => FALSE,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'IAEA' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'IAEA',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-n18E4x0qRRaIP7nV6I0SDYiCJsq77HCB'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'n18E4x0qRRaIP7nV6I0SDYiCJsq77HCB',
    'disabled' => FALSE,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'IAEA' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'IAEA',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-odQxTWyhGW1WU7Sl00ISAnQ21BCdJG3A'] = array(
    'cache' => -1,
    'css_class' => '',
    'custom' => 0,
    'delta' => 'odQxTWyhGW1WU7Sl00ISAnQ21BCdJG3A',
    'disabled' => FALSE,
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'IAEA' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'IAEA',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
